from django.core.exceptions import ValidationError


zip_codes = [33012, 33186, 33015, 33157, 33033, 33142, 33125, 33177, 33165, 33161, 33018,
             33175, 33196, 33178, 33032, 33176, 33016, 33126, 33029, 33193, 33155, 33147,
             33169, 33162, 33010, 33179, 33172, 33134, 33055, 33014, 33135, 33160, 33141,
             33139, 33183, 33056, 33030, 33133, 33156, 33013, 33127, 33180, 33173, 33174,
             33145, 33144, 33143, 33130, 33150, 33185, 33054, 33138, 33168, 33189, 33034,
             33166, 33167, 33184, 33140, 33181, 33187, 33131, 33132, 33137, 33136, 33146,
             33154, 33182, 33129, 33170, 33149, 33037, 33190, 33194, 33035, 33128, 33031,
             33158, 33122, 33199, 33039, 33109, 33002, 33011, 33017, 33090, 33093, 33092,
             33101, 33107, 33102, 33110, 33112, 33111, 33116, 33114, 33121, 33119, 33124,
             33148, 33152, 33151, 33153, 33159, 33164, 33163, 33188, 33192, 33197, 33233,
             33231, 33238, 33234, 33242, 33239, 33245, 33243, 33255, 33247, 33257, 33256,
             33265, 33261, 33269, 33266, 33283, 33280, 33299, 33296, 33191, 33206, 33198,
             33195, 33222, 33106]


def zipusa(value):
    if int(value) not in zip_codes:
        raise ValidationError("Wrong zipcode only support USA zipcode")
